---
- hosts: fiapServerAws
  remote_user: root
  tasks:
    - name: 'Instalanado o java'
      apt: name ={{ item }} state=present
      with_items:
            - openjdk-8-jdk -y
            - openjdk-8-jre -y
            - nginx
            - clean all
    - name: 'Start nginx server'
      service:
        name: nginx
        state: start
    - name: 'Configure nginx'
      bar:
        - server_name ansible: ansible
        - listen: 8089
        - location: localhost /
        - root: /home/user/JAVA-ADVANCED-FRAMEWORKS/StrategyPatterns
        - index: index.html
...
